CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[Person_Id] INT NOT NULL,
    [LoginId] VARCHAR(100) NOT NULL, 
    [Password] VARCHAR(20) NOT NULL, 
    [RowStatus] TINYINT NOT NULL, 
    [UpdatedBy] INT NOT NULL, 
    [UpdatedDate] DATETIME2(2) GENERATED ALWAYS AS ROW START,
	[ValidToDate] DATETIME2(2) GENERATED ALWAYS AS ROW END,
	PERIOD FOR SYSTEM_TIME (UpdatedDate, ValidToDate), 
    CONSTRAINT [FK_User_Person] FOREIGN KEY ([Person_Id]) REFERENCES [Person]([Id])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.UserHistory))
GO
